### ISSUE TITLE
Client side router for maverick

### ISSUE THREAD

**Issue by ansarizafar** [maverick-js/maverick#1]
Maverick looks promising. Is there any plan to build a client side router or an adapter for TankStack router https://github.com/TanStack/router ?

**Comment by mihar-22** [comment]
Hey @ansarizafar! 

Short answer: not yet.

It'll definitely be possible to build apps with Maverick but I haven't really focused on that use-case. It's mostly been about making a petite or slimmed down version of Solid.js, so I can then extend it to build UI libraries that work across meta-frameworks.

Unfortunately my plate is going to be full so I can't see myself finding time in the next few months to build that kind of integration. After I publicly release Maverick if any one wants to build it then I'll try to chime in as much as possible.

**Comment by mihar-22** [comment]
Forgot to mention...

I'm also working on a framework-agnostic tool for building apps/docs on the side called [Vessel](https://github.com/vessel-js/vessel). It already has a framework-agnostic client-side router and handles all the fancy loader/action stuff. I'll most likely integrate Maverick there if time permits. It'll definitely be the easiest way to build apps using it.

**Comment by ansarizafar** [comment]
I am looking for a web components framework for building a SPA. I am 
 currently playing with https://hybrids.js.org and Microsoft Fast and planing to use https://surrealdb.com/ for the backend.
