### ISSUE TITLE
How to build UI and web components using Maverick.js? Are there any documentation available?

### ISSUE THREAD

**Issue by mdsohelmia** [maverick-js/maverick#4]

**Comment by mihar-22** [comment]
Unfortunately not right at this time @mdsohelmia. I plan on doing it right after our player 1.0 so I know Maverick is stable. What were you hoping to use the library for?

**Comment by mdsohelmia** [comment]
@mihar-22  Thanks for your reply.
We are developing an improved player UI for the Shaka player.
