### ISSUE TITLE
What actually is maverick?

### ISSUE THREAD

**Issue by baseplate-admin** [maverick-js/maverick#5]
Hi i have seen that maverick is using [react](https://github.com/maverick-js/maverick/tree/a71b0b5f2eee5bf7147e93f8c83e26313fb445c7/packages/maverick/src/react) [under](https://github.com/maverick-js/maverick/blob/a71b0b5f2eee5bf7147e93f8c83e26313fb445c7/packages/maverick/package.json#L51) [the hood](https://github.com/maverick-js/maverick/blob/a71b0b5f2eee5bf7147e93f8c83e26313fb445c7/packages/maverick/package.json#L52), so my question is:

What actually is maverick?

Is it a web-component wrapper for react?

**Comment by mihar-22** [comment]
**Short Answer:** Maverick is being built so you can use one component and reactivity model that maps to multiple frameworks.

---

Maverick is a component system powered under the hood by it's own fast reactivity model ([signals](https://github.com/maverick-js/signals)). It's designed to map to a host such as a Custom Element or a framework component (e.g., React, Vue). Rendering is delegated to frameworks and we focus on managing and forwarding state updates, offloading attribute/class/style bindings, auto-memoizing expressions and DOM updates, and anything else we can in Maverick to improve performance.

I'm in phase one which only contains Custom Elements and React with a lot of duplicate manual work which you can see in our player library (vidstack) as it doesn't have the full-blown compiler yet... but I'm starting to plan that part out right now. Ideally, you'll write a class component once using signals under the hood for props/state/hooks, JSX for markup, and then the compiler will output performant framework-specific components. It'll also go as far as binding context between our system and the host.

Close alternative is Mitosis but from my understanding it's just a "basic" compiler that maps JSX to each framework target. It doesn't have it's own components or reactivity model and it doesn't offload any work. It's still really close but the main goal here is to have one underlying component and reactivity system that binds itself to a host.

**Comment by baseplate-admin** [comment]
Thanks for Such a detailed explanation.
